[package]
name = "rapier3d_stress_test1"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.3", features = [ "webgl2" ] }
bevy_rapier3d = { version = "*", features = [ "simd-stable", "debug-render-3d" ] }

[build]
target = "index.html"